FROM alpine

RUN apk add --update --no-cache build-base linux-headers cmake python3 python3-dev postgresql-dev 
RUN pip3 install --upgrade pip setuptools

WORKDIR /code
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY api.py ./

CMD ["python3", "-u", "api.py"]
